# CNN Model Creation

In [110]:
import numpy as np
import pandas as pd
import tensorflow as tf
# from keras import Input, activations, regularizers
# from keras.callbacks import ModelCheckpoint
# from keras.layers import Dense, Flatten, Conv2D, MaxPool2D, Dropout
# from keras.losses import CategoricalCrossentropy
# from keras.models import Sequential
# from keras.datasets import cifar10
from sklearn.preprocessing import LabelBinarizer

In [111]:
# Data Preparation and Processing
data = tf.keras.datasets.cifar10.load_data()
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()

X_train = X_train / 255.0
X_test = X_test / 255.0

#Target transformation
output_encoder = LabelBinarizer()
y_train = output_encoder.fit_transform(y_train)
y_test = output_encoder.transform(y_test)

 # Shapes of data variables
print("X_train shape: ", X_train.shape)
print("y_train shape: ", y_train.shape)
print("X_test shape: ", X_test.shape)
print("y_test shape: ", y_test.shape)

X_train shape:  (50000, 32, 32, 3)
y_train shape:  (50000, 10)
X_test shape:  (10000, 32, 32, 3)
y_test shape:  (10000, 10)


In [112]:
print(output_encoder.classes_)

[0 1 2 3 4 5 6 7 8 9]


In [113]:
X_train.shape[1:4]

(32, 32, 3)

In [114]:
print(X_train[1])

[[[0.60392157 0.69411765 0.73333333]
  [0.49411765 0.5372549  0.53333333]
  [0.41176471 0.40784314 0.37254902]
  ...
  [0.35686275 0.37254902 0.27843137]
  [0.34117647 0.35294118 0.27843137]
  [0.30980392 0.31764706 0.2745098 ]]

 [[0.54901961 0.62745098 0.6627451 ]
  [0.56862745 0.6        0.60392157]
  [0.49019608 0.49019608 0.4627451 ]
  ...
  [0.37647059 0.38823529 0.30588235]
  [0.30196078 0.31372549 0.24313725]
  [0.27843137 0.28627451 0.23921569]]

 [[0.54901961 0.60784314 0.64313725]
  [0.54509804 0.57254902 0.58431373]
  [0.45098039 0.45098039 0.43921569]
  ...
  [0.30980392 0.32156863 0.25098039]
  [0.26666667 0.2745098  0.21568627]
  [0.2627451  0.27058824 0.21568627]]

 ...

 [[0.68627451 0.65490196 0.65098039]
  [0.61176471 0.60392157 0.62745098]
  [0.60392157 0.62745098 0.66666667]
  ...
  [0.16470588 0.13333333 0.14117647]
  [0.23921569 0.20784314 0.22352941]
  [0.36470588 0.3254902  0.35686275]]

 [[0.64705882 0.60392157 0.50196078]
  [0.61176471 0.59607843 0.50980392]


In [115]:
callbacks = []
epochs = 10
batch_size = 100

# Create callbacks
checkpoint = tf.keras.callbacks.ModelCheckpoint(
    f"conv_weights/Conv2D Model/{epochs}e-{batch_size}bs" + "-{loss:.4f}" + ".keras", 
    monitor='loss', 
    verbose=1,
    save_best_only=True, mode='min')

earlyStopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',  # Metric to monitor
    patience=3,          # Number of epochs with no improvement after which training stops
    min_delta=0.001,     # Minimum change to qualify as an improvement
    mode='min',          # The monitored quantity should be minimized (e.g., loss)
    verbose=1,           # Log when the callback takes action
    restore_best_weights=True # Restores model weights from the best epoch
)
callbacks = [checkpoint]

In [116]:
#Model Creation

model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(filters=100, kernel_size=(3,3), activation=tf.keras.activations.relu),
    tf.keras.layers.Conv2D(filters=40, kernel_size=(3,3), activation=tf.keras.activations.relu),
    tf.keras.layers.MaxPool2D(pool_size=(2,2)),
    tf.keras.layers.Conv2D(filters=30, kernel_size=(5,5), activation=tf.keras.activations.relu),

    # tf.keras.layers.Conv2D(filters=40, kernel_size=(5,5), activation=tf.keras.activations.relu),
    tf.keras.layers.MaxPool2D(pool_size=(2,2)),
    tf.keras.layers.Conv2D(filters=30, kernel_size=(5,5), padding='same', activation=tf.keras.activations.relu),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(units=30, activation=tf.keras.activations.relu),
    tf.keras.layers.Dense(units=10, activation=tf.keras.activations.softmax)
])
model.build(input_shape=(None,) + X_train.shape[1:4])
print(model.summary())

Model: "sequential_55"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_215 (Conv2D)             │ (None, 30, 30, 100)    │         2,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_216 (Conv2D)             │ (None, 28, 28, 40)     │        36,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_101               │ (None, 14, 14, 40)     │             0 │
│ (MaxPooling2D)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_217 (Conv2D)             │ (None, 10, 10, 30)     │        30,030 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_102               │ (None, 5, 5, 30)       │             0 │
│ (MaxPooling2D)                  │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_218 (Conv2D)             │ (None, 5, 5, 30)       │        22,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_55 (Flatten)            │ (None, 750)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_98 (Dense)                │ (None, 30)             │        22,530 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_99 (Dense)                │ (None, 10)             │           310 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 114,240 (446.25 KB)

 Trainable params: 114,240 (446.25 KB)

 Non-trainable params: 0 (0.00 B)

None


In [117]:
model.compile(optimizer='adam', loss=tf.keras.losses.CategoricalCrossentropy(), metrics=['accuracy'])
# model.load_weights("conv_weights/Conv2D Model/20e-100bs-0.9729.keras")
model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size, shuffle=False, callbacks=callbacks, verbose=1, validation_split=0.1)

Epoch 1/10
450/450 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.2682 - loss: 1.9550
Epoch 1: loss improved from None to 1.72868, saving model to conv_weights/Conv2D Model/10e-100bs-1.7287.keras
450/450 ━━━━━━━━━━━━━━━━━━━━ 45s 97ms/step - accuracy: 0.3634 - loss: 1.7287 - val_accuracy: 0.4996 - val_loss: 1.3990
Epoch 2/10
450/450 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5159 - loss: 1.3538
Epoch 2: loss improved from 1.72868 to 1.30940, saving model to conv_weights/Conv2D Model/10e-100bs-1.3094.keras
450/450 ━━━━━━━━━━━━━━━━━━━━ 38s 85ms/step - accuracy: 0.5325 - loss: 1.3094 - val_accuracy: 0.5538 - val_loss: 1.2472
Epoch 3/10
450/450 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5891 - loss: 1.1609
Epoch 3: loss improved from 1.30940 to 1.13324, saving model to conv_weights/Conv2D Model/10e-100bs-1.1332.keras
450/450 ━━━━━━━━━━━━━━━━━━━━ 41s 91ms/step - accuracy: 0.5988 - loss: 1.1332 - val_accuracy: 0.6288 - val_loss: 1.0739
Epoch 4/10
450/450 ━━━━━━━━━━━━━━━━━━━━ 0s 86m

In [ ]:
predictions = model.predict(X_train[:10])
pred_decode = output_encoder.inverse_transform(predictions)
print(pred_decode)
print(output_encoder.inverse_transform(y_train[:10]))

In [ ]:
# import tensorflow as tf
# converter = tf.lite.TFLiteConverter.from_keras_model(model) # or .from_saved_model(saved_model_dir)
# tflite_model = converter.convert()
# with open('model.tflite', 'wb') as f:
#     f.write(tflite_model)

Saved artifact at '/var/folders/0_/nmh5w64x3q5_ffwfkr35sscw0000gn/T/tmphi4ywg6h'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 32, 32, 3), dtype=tf.float32, name='keras_tensor_43')
Output Type:
  TensorSpec(shape=(None, 10), dtype=tf.float32, name=None)
Captures:
  4895227984: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895229136: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895229712: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895229904: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895230096: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895230480: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895230288: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895230864: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895230672: TensorSpec(shape=(), dtype=tf.resource, name=None)
  4895231248: TensorSpec(shape=(), dtype=tf.resource, name=None)


W0000 00:00:1766688857.598078  212361 tf_tfl_flatbuffer_helpers.cc:364] Ignored output_format.
W0000 00:00:1766688857.598484  212361 tf_tfl_flatbuffer_helpers.cc:367] Ignored drop_control_dependency.
I0000 00:00:1766688857.608609  212361 mlir_graph_optimization_pass.cc:437] MLIR V1 optimization pass is not enabled


In [20]:
# Save the model to a .h5 file
model.save("object_classifier_model4.keras")

In [101]:
model.output_names = ['output']

In [102]:
import coremltools as ct


# # Convert the model
# mlmodel = ct.convert(
#     'object_classifier_model4.h5',
#     convert_to="mlprogram", # Use mlprogram for better performance on newer iOS versions
#     minimum_deployment_target=ct.target.iOS15, # Specify your minimum iOS target
#     source="tensorflow"
# )

image_input = ct.converters.mil.input_types.ImageType(
    name='input_image', 
    shape=(1, 3, 224, 224), 
    scale=1.0/255.0, 
    bias=[0.0, 0.0, 0.0], 
    color_layout='RGB'
)

mlmodel = ct.converters.convert(model=model, 
                     inputs=[image_input], 
                     source="auto", convert_to="mlprogram", 
                     minimum_deployment_target=ct.target.iOS16)

# mlmodel = ct.convert(model=model, 
#                      inputs=[ct.TensorType(dtype=np.float16)], 
#                      source="tensorflow", convert_to="mlprogram", 
#                      minimum_deployment_target=ct.target.iOS16,
#                      output_names=['output'])
# Save the converted model
mlmodel.save("ObjectClassifierModel.mlpackage")

TensorFlow version 2.20.0 has not been tested with coremltools. You may run into unexpected errors. TensorFlow 2.12.0 is the most recent version that has been tested.
I0000 00:00:1767062541.593652  261481 devices.cc:76] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
I0000 00:00:1767062541.595610  261481 single_machine.cc:376] Starting new session
I0000 00:00:1767062541.630193  261481 devices.cc:76] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
I0000 00:00:1767062541.630246  261481 single_machine.cc:376] Starting new session
I0000 00:00:1767062541.661509  261481 devices.cc:76] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA or ROCm support)
I0000 00:00:1767062541.661555  261481 single_machine.cc:376] Starting new session
I0000 00:00:1767062541.681

ValueError: Input (input_image) provided is not found in given tensorflow graph. Placeholders in graph are: ['keras_tensor_402']